#!/usr/bin/env python3
"""Generate C++ asset headers for the standalone World Cup firmware.

Reads the baked source assets under assets/:
  - assets/flags.json        (flag bitmaps + per-team accent colors)
  - assets/geist-native.json (big numeral glyphs)

and emits:
  src/gen/flags_data.h  — flag bitmaps (raw RGB, row-major) + accents + index
  src/gen/geist_data.h  — numeral glyph bitmaps (0-9 and '-') + metrics

On the ESP32-S3 plain `const` arrays land in memory-mapped flash and are
directly addressable, so no PROGMEM/pgm_read indirection is needed.

Run from anywhere:  python3 tools/gen_assets.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.abspath(os.path.join(HERE, ".."))  # firmware root
FLAGS_JSON = os.path.join(PROJ, "assets", "flags.json")
GEIST_JSON = os.path.join(PROJ, "assets", "geist-native.json")
OUT_DIR = os.path.join(HERE, "..", "src", "gen")

# The three baked board sizes (w, h), in the order Flags blits them verbatim.
SIZES = [(10, 7), (12, 8), (26, 17)]

# Geist big numerals are used only for scores -> digits and the minus sign.
GEIST_CHARS = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "-"]


def hex_to_bytes(hexstr):
    return bytes.fromhex(hexstr)


def emit_byte_array(out, name, data):
    out.append(f"static const uint8_t {name}[] = {{")
    line = "  "
    for i, b in enumerate(data):
        line += f"{b},"
        if (i + 1) % 20 == 0:
            out.append(line)
            line = "  "
    if line.strip():
        out.append(line)
    out.append("};")


def gen_flags():
    flags = json.load(open(FLAGS_JSON))
    codes = sorted(flags.keys())
    out = []
    out.append("// Generated by tools/gen_assets.py from priv/matrix/flags.json — do not edit.")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")

    # Per-code, per-size pixel arrays.
    for code in codes:
        sizes = flags[code]["sizes"]
        for (w, h) in SIZES:
            key = f"{w}x{h}"
            data = hex_to_bytes(sizes[key])
            assert len(data) == w * h * 3, (code, key, len(data))
            emit_byte_array(out, f"flag_{code}_{w}x{h}", data)
    out.append("")

    out.append("struct FlagEntry {")
    out.append("  char code[4];")
    out.append("  const uint8_t* px10x7;")
    out.append("  const uint8_t* px12x8;")
    out.append("  const uint8_t* px26x17;")
    out.append("  uint8_t ar, ag, ab;  // accent color")
    out.append("};")
    out.append("")
    out.append("static const FlagEntry FLAGS[] = {")
    for code in codes:
        acc = hex_to_bytes(flags[code]["accent"])
        out.append(
            f'  {{"{code}", flag_{code}_10x7, flag_{code}_12x8, flag_{code}_26x17, '
            f"{acc[0]}, {acc[1]}, {acc[2]}}},"
        )
    out.append("};")
    out.append(f"static const int FLAG_COUNT = {len(codes)};")
    out.append("")
    return "\n".join(out) + "\n", len(codes)


def gen_geist():
    geist = json.load(open(GEIST_JSON))
    meta = geist["meta"]
    glyphs = geist["glyphs"]
    cap = meta["cap_height_cells"]
    space_adv = glyphs.get(" ", {}).get("advance", 10)

    out = []
    out.append("// Generated by tools/gen_assets.py from priv/matrix/geist-native.json — do not edit.")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"static const int GEIST_CAP_HEIGHT = {cap};")
    out.append(f"static const int GEIST_SPACE_ADV = {space_adv};")
    out.append("")

    safe = {"-": "minus"}
    for ch in GEIST_CHARS:
        g = glyphs[ch]
        bm = g["bitmap"]  # list of rows, each a list of 0/1
        h = len(bm)
        w = len(bm[0]) if h else 0
        assert w == g["width"], (ch, w, g["width"])
        flat = [cell for row in bm for cell in row]
        name = safe.get(ch, ch)
        emit_byte_array(out, f"geist_bits_{name}", flat)
    out.append("")

    out.append("struct GeistGlyph {")
    out.append("  char ch;")
    out.append("  uint8_t width, height;")
    out.append("  uint8_t advance, xoff, yoff;")
    out.append("  const uint8_t* bits;  // height*width, row-major 0/1")
    out.append("};")
    out.append("")
    out.append("static const GeistGlyph GEIST_GLYPHS[] = {")
    for ch in GEIST_CHARS:
        g = glyphs[ch]
        name = safe.get(ch, ch)
        lit = f"'{ch}'"
        out.append(
            f"  {{{lit}, {g['width']}, {len(g['bitmap'])}, {g['advance']}, "
            f"{g['xoff']}, {g['yoff']}, geist_bits_{name}}},"
        )
    out.append("};")
    out.append(f"static const int GEIST_GLYPH_COUNT = {len(GEIST_CHARS)};")
    out.append("")
    return "\n".join(out) + "\n", len(GEIST_CHARS)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    flags_src, n_flags = gen_flags()
    geist_src, n_geist = gen_geist()

    with open(os.path.join(OUT_DIR, "flags_data.h"), "w") as f:
        f.write(flags_src)
    with open(os.path.join(OUT_DIR, "geist_data.h"), "w") as f:
        f.write(geist_src)

    print(f"wrote flags_data.h: {n_flags} flags x {len(SIZES)} sizes")
    print(f"wrote geist_data.h: {n_geist} glyphs")


if __name__ == "__main__":
    main()
