defmodule WorldCupTracker.Matrix.Flags do
  @moduledoc """
  Designer pixel-art LED flags for the 128×64 panel, baked from
  `priv/matrix/flags.json` (generated by `tools/gen_flags.py` from the
  hand-tuned exports in `assets/flags/`).

  Each of the 48 team codes carries three pre-baked bitmaps at exactly the
  sizes the boards draw: 26×17 (hero), 12×8 (goal ribbon) and 10×7 (rows).
  `draw/6` blits those verbatim; any other size is nearest-neighbor scaled
  from the 26×17 art.

  Asset conventions: flags are ~3:2, fully opaque, LED-tuned (bright,
  single-chroma, no federation crests). "Black" flag fields are drawn as a
  DIM grey (`#262b38`), not true black — on a real panel a black stripe is
  just unlit LEDs and would vanish, so the assets light it faintly so the
  band is actually visible (Germany, Belgium).
  """

  alias WorldCupTracker.Matrix.Framebuffer

  @json_path Application.app_dir(:world_cup_tracker, "priv/matrix/flags.json")
  @external_resource @json_path

  # Bake each flat row-major "RRGGBB…" hex string into a raw binary —
  # 3 bytes per pixel — keyed by {code, {w, h}}. Compact and pattern-matchable.
  @bitmaps Map.new(Jason.decode!(File.read!(@json_path)), fn {code, %{"sizes" => sizes}} ->
             {code,
              Map.new(sizes, fn {size_key, hex} ->
                [w, h] = size_key |> String.split("x") |> Enum.map(&String.to_integer/1)
                {{w, h}, Base.decode16!(hex, case: :lower)}
              end)}
           end)

  @codes @bitmaps |> Map.keys() |> Enum.sort()

  # Hero art dimensions — the source for nearest-neighbor scaling.
  @base_w 26
  @base_h 17

  # Unknown-code checker box colors (as the JS reference does): alternating
  # grey / dim-grey "black".
  @grey {0x3A, 0x41, 0x50}
  @dim_black {0x26, 0x2B, 0x38}

  @doc """
  Draw flag `code` into `fb` at `(ox, oy)`, `w`×`h`. The three board sizes
  (26×17, 12×8, 10×7) blit their baked bitmap verbatim; any other size is
  nearest-neighbor scaled from the 26×17 art. Unknown code → grey checker
  box. `Framebuffer.set/4` clips off-panel writes, so no bounds checks are
  needed here.
  """
  @spec draw(Framebuffer.t(), integer, integer, pos_integer, pos_integer, String.t()) ::
          Framebuffer.t()
  def draw(fb, ox, oy, w, h, code) do
    case @bitmaps[code] do
      nil -> checker(fb, ox, oy, w, h)
      sizes -> draw_known(fb, ox, oy, w, h, sizes)
    end
  end

  defp draw_known(fb, ox, oy, w, h, sizes) do
    case sizes[{w, h}] do
      nil -> scale_blit(fb, ox, oy, w, h, Map.fetch!(sizes, {@base_w, @base_h}))
      bin -> blit(fb, ox, oy, w, bin)
    end
  end

  @doc "Whether a baked bitmap exists for `code`."
  @spec has?(String.t()) :: boolean
  def has?(code), do: is_map_key(@bitmaps, code)

  @doc "All 48 flag codes, sorted."
  @spec codes() :: [String.t()]
  def codes, do: @codes

  # 1:1 blit of a baked row-major RGB binary.
  defp blit(fb, ox, oy, w, bin) do
    for i <- 0..(div(byte_size(bin), 3) - 1)//1, reduce: fb do
      acc ->
        <<r, g, b>> = binary_part(bin, i * 3, 3)
        Framebuffer.set(acc, ox + rem(i, w), oy + div(i, w), {r, g, b})
    end
  end

  # Nearest-neighbor scale from the 26×17 hero art:
  # source px = {floor(fx·26/w), floor(fy·17/h)}.
  defp scale_blit(fb, ox, oy, w, h, base) do
    for fy <- 0..(h - 1)//1, fx <- 0..(w - 1)//1, reduce: fb do
      acc ->
        sx = div(fx * @base_w, w)
        sy = div(fy * @base_h, h)
        <<r, g, b>> = binary_part(base, (sy * @base_w + sx) * 3, 3)
        Framebuffer.set(acc, ox + fx, oy + fy, {r, g, b})
    end
  end

  defp checker(fb, ox, oy, w, h) do
    for fy <- 0..(h - 1)//1, fx <- 0..(w - 1)//1, reduce: fb do
      acc ->
        c = if rem(fx + fy, 2) == 1, do: @grey, else: @dim_black
        Framebuffer.set(acc, ox + fx, oy + fy, c)
    end
  end
end
